In [1]:
import cv2
import numpy as np

In [2]:
def av_pix(img,circles,size):
    av_value = []
    for coords in circles[0,:]:
        col = np.mean(img[coords[1]-size:coords[1]+size,coords[0]-size:coords[0]+size])
        #print(img[coords[1]-size:coords[1]+size,coords[0]-size:coords[0]+size])
        av_value.append(col)
    return av_value   

In [3]:
def get_radius(circles):
    radius = []
    for coords in circles[0,:]:
        radius.append(coords[2])    
    return radius

In [4]:
img = cv2.imread('coins.png',cv2.IMREAD_GRAYSCALE)
original_image = cv2.imread('coins.png',1)
img = cv2.GaussianBlur(img, (5,5), 0)

In [5]:
circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,0.9,120,param1=50,param2=27,minRadius=60,maxRadius=120)

print(circles)

[[[1059.5  199.5   96. ]
  [1108.5  499.5   99.3]
  [1311.5  397.5  103.3]
  [ 981.5  365.5   82.7]
  [ 763.5  500.5   79.9]
  [ 776.5  104.5   83.6]
  [ 939.5  580.5   80.7]
  [1271.5  219.5   67.3]]]


In [6]:
circles = np.uint16(np.around(circles))
count = 1
for i in circles[0,:]:
    
    # draw the outer circle
    cv2.circle(original_image,(i[0],i[1]),i[2],(0,255,0),2)
    # draw the center of the circle
    cv2.circle(original_image,(i[0],i[1]),2,(0,0,255),3)
    #cv2.putText(original_image, str(count),(i[0],i[1]), cv2.FONT_HERSHEY_SIMPLEX, 2, (0,0,0), 2)
    count += 1          

In [7]:
radii = get_radius(circles)
print(radii)

[96, 99, 103, 83, 80, 84, 81, 67]


In [8]:
bright_values = av_pix(img,circles,20)
print(bright_values)

[179.844375, 85.68625, 97.176875, 131.384375, 73.96875, 101.205625, 75.08125, 181.275625]


In [9]:
values = []
for a,b in zip(bright_values,radii):
    if a > 150 and b > 90:
        values.append(10)
    elif a > 150 and b <= 90:
        values.append(5)
    elif a < 150 and b > 90:
        values.append(2)
    elif a < 150 and b < 90:
        values.append(1)        
print(values) 

[10, 2, 2, 1, 1, 1, 1, 5]


In [10]:
count_2 = 0
for i in circles[0,:]:
    
    cv2.putText(original_image, str(values[count_2]) + 'p',(i[0],i[1]), cv2.FONT_HERSHEY_SIMPLEX, 2, (0,0,0), 2)
    count_2 += 1
cv2.putText(original_image, 'ESTIMATED TOTAL VALUE: ' + str(sum(values)) + 'p', (200,100), cv2.FONT_HERSHEY_SIMPLEX, 1.3, 255)

array([[[159, 148, 147],
        [161, 149, 148],
        [162, 151, 150],
        ...,
        [162, 156, 159],
        [158, 152, 155],
        [155, 151, 154]],

       [[158, 147, 145],
        [162, 151, 149],
        [166, 155, 154],
        ...,
        [160, 155, 157],
        [159, 154, 156],
        [155, 150, 152]],

       [[168, 158, 154],
        [165, 154, 151],
        [162, 151, 150],
        ...,
        [159, 155, 155],
        [160, 155, 155],
        [154, 150, 149]],

       ...,

       [[165, 156, 146],
        [172, 162, 155],
        [170, 160, 156],
        ...,
        [176, 170, 168],
        [180, 173, 173],
        [176, 169, 169]],

       [[160, 151, 142],
        [167, 158, 148],
        [172, 161, 156],
        ...,
        [178, 171, 170],
        [172, 166, 165],
        [176, 169, 170]],

       [[174, 164, 160],
        [170, 158, 155],
        [172, 158, 155],
        ...,
        [173, 168, 169],
        [172, 168, 168],
        [175, 171, 171]]

In [11]:
cv2.imshow('Detected Coins',original_image)
cv2.waitKey(0)
cv2.destroyAllWindows()